#OBTENER MATERIAS Y CODIGOS
library(dplyr)
library(xlsx)
library(readxl)
setwd("C:/Users/Charles/Desktop/ESPOL/Semestre 7/Metodología de la Investigacion/Proyecto/Git/MetodologiaProyecto/Script en R")
datos <- read_excel("graduados.xlsx",sheet = 1)
#datos <- data.frame(datos)
materias <- distinct(datos,datos$`nombre materia`, datos$codigomateria)
View(materias)
write.xlsx(materias,"./listado_materias.xlsx","materias")
